### ISSUE TITLE
Add docs reference info

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/blazor-samples#11]
Add docs sample reference info will allow it to show up in samples, which only has 1 thing in it today :( https://docs.microsoft.com/en-us/samples/browse/?expanded=dotnet&products=blazor

See: https://github.com/dotnet/EntityFramework.Docs/blob/main/samples/end2end/PlanetaryDocs/README.md
for example: 

```
---
page_type: sample
description: "This repository is intended to showcase a full application that supports Create, Read, Update, and Delete operations (CRUD) using Blazor (Server), Entity Framework Core and Azure Cosmos DB."
languages:
- csharp
products:
- dotnet-core
- ef-core
- blazor
- azure-cosmos-db
---
```

**Comment by guardrex** [comment]
Thanks @jamesmontemagno ... *Sorry for the delay!* I just found these issues over here. These samples are all linked into the Blazor doc set of the `dotnet/AspNetCore.Docs` repo, and that's where we normally work and receive pings on issues. I'll see if I can address this today (6/16).

**Comment by guardrex** [comment]
😕 ... I'll research further because I already have the following in the README.md file without this repo appearing in the search results as you say ...

```
---
page_type: sample
languages:
  - csharp
  - razor
products:
  - aspnet-core
  - blazor
name: Blazor sample applications
urlFragment: blazor-samples
description: "Samples to accompany the official Microsoft Blazor documentation."
---
```

**Comment by guardrex** [comment]
I wonder if that indentation is hosing it. I'll remove the indentation (at least).

**Comment by guardrex** [comment]
Hummmmm ...

https://docs.microsoft.com/en-us/samples/browse/?expanded=dotnet&products=blazor

There might be a delay given that I just added the `dotnet-core` entry. Or, there might be a management gesture required. I've pinged Rick and Wade offline for assistance.

**Comment by guardrex** [comment]
UPDATE: Looks like the repo isn't picked up automatically. It will need to be tagged internally somehow. We're working on it internally.

**Comment by jamesmontemagno** [comment]
Will ping @jongalloway  who can help here

**Comment by jongalloway** [comment]
There's also a form that needs to be submitted once per repo, once that's done the repo is scanned for docs with frontmatter as part of the process. I submitted for this repo.

**Comment by jongalloway** [comment]
Showing up in review now: https://review.docs.microsoft.com/en-us/samples/browse/?branch=main&expanded=dotnet&products=blazor
