### ISSUE TITLE
Logout not Working (BlazorWebAssemblyStandaloneWithIdentity)

### ISSUE THREAD

**Issue by Softwerker04** [dotnet/blazor-samples#132]
**Describe the issue**
After register a new user and login the logout is not working. The screen is flickering and the user is not logged out.

**To Reproduce**
1. Create a new project map with regarding projects (Backend and BlazorWasmAuth)
2. Set both project as start projects
3. Register a new user
4. Login for new user
5. Try to logout

**Expected behavior**
User should become logged out

**.NET Version**
8.0.100

---
#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment]
Thanks @Softwerker04 ... I'll take a look. We just performed an update that might have accidentally broken it.

**Comment by guardrex** [comment]
Yep! ***We broke it!*** Jeremy is the sample author, and he supplied some code to prevent posting anything but an empty JSON message `{}`, and that code that he sent over seems to have broken the logout. *Stand-by ....* if I don't see the resolution, I'll ping him to take a look.

**Comment by guardrex** [comment]
@JeremyLikness ... The logout code that you sent is failing, placing the logout in a nasty loop on the following exception ...

>  Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
> An unhandled exception has occurred while executing the request.
> Microsoft.AspNetCore.Http.BadHttpRequestException: Expected a supported JSON media type but got "".

**Comment by guardrex** [comment]
@Softwerker04 ... Until Jeremy comes in with a fix, you can change to the prior code. You can see it on the PR diff ......

https://github.com/dotnet/blazor-samples/pull/130/files

**Comment by guardrex** [comment]
Jeremy, the code is ...

```csharp
app.MapPost("/logout", async (
    SignInManager<AppUser> signInManager,
    [FromBody]object empty) =>
{
    if (empty is not null)
    {
        await signInManager.SignOutAsync();
        return Results.Ok();
    }
    return Results.NotFound();
}).RequireAuthorization();
```

... and I've temporarily reverted back to the prior code for now with a note (code comment) to see this issue.

**Comment by Softwerker04** [comment]
@guardrex, @JeremyLikness After changing the handler for logout endpoint the mechanism seems to work. Great job, thanks a lot for your support!!!

**Comment by PedrooNL** [comment]
> @guardrex, @JeremyLikness After changing the handler for logout endpoint the mechanism seems to work. Great job, thanks a lot for your support!!!
@Softwerker04 Can you explain what you did? Having the same issue.

**Comment by PedrooNL** [comment]
> @guardrex, @JeremyLikness After changing the handler for logout endpoint the mechanism seems to work. Great job, thanks a lot for your support!!!

 @Softwerker04  Can you explain what you did? Having the same issue.
