### ISSUE TITLE
Use of Deprecated Package

### ISSUE THREAD

**Issue by MrChriZ** [dotnet/blazor-samples#134]
**Describe the issue**
In your new BlazorWebAssemblyStandaloneWithIdentity project, in the backend you appear to be using the now deprecated package 
Microsoft.AspNetCore.Identity 2.2.0?

Am I missing something?

**To Reproduce**
Open project and look at dependancies.

**Expected behavior**
No deprecated dependancies

**Screenshots**
![2023-12-08_16-06](https://github.com/dotnet/blazor-samples/assets/3593276/bc026e8f-12b9-42b7-801f-743b8b74343a)

**Additional context**
Add any other context about the issue here.

**.NET Version**
8.0

---
#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment]
No, that's the latest version of that package. That one doesn't version with a number that matches the shared framework.

https://www.nuget.org/packages/Microsoft.AspNetCore.Identity

**Comment by MrChriZ** [comment]
It would be good to have some clarity.  I've used it in a .NET 7 project already directly and I've seen posts across the web where people are unsure about what they should be using in place of Microsoft.AspNetCore.Identity - or if it is good to continue using it.

**Comment by guardrex** [comment]
Ok ... we're good now ... fixed on commit ...

https://github.com/dotnet/blazor-samples/commit/9f7ea512e4e807365ce2b4d92cca38fe456b084b

Thanks for opening this issue!

**Comment by MrChriZ** [comment]
Thanks - I think if you just remove the package you'll have the following error:
Error	CS0246	The type or namespace name 'ClaimsPrincipal' could not be found (are you missing a using directive or an assembly reference?)	Program.cs

potentially this can be resolved by referencing System.Security.Claims

**Comment by MrChriZ** [comment]
That's simply downloading your repository.  No code changed.

**Comment by MrChriZ** [comment]
And sorry it's in the 8.0 Backend project as per my original screenshot.

**Comment by guardrex** [comment]
I agree. We needed this for ***years*** ... and was asked for it quite a bit. We do need the roles piece for sure. However ... even in this form ... it shoudn't be too difficult for folks to roll their own controller into the backend and send back role claims for use by the frontend.

We're going to leave the extra coverage on the other scenarios/endpoints (e.g., 2FA) over in the main doc set. That coverage is being worked on now at ...

https://github.com/dotnet/AspNetCore.Docs/pull/31197

What I don't know is if they'll relent and provide a fully working implementation for token auth. Right now, they just guide toward it with notes and a partial implementation. I'm telling them on ...

https://github.com/dotnet/AspNetCore.Docs/pull/31214

... that I think it should be fully worked out and presented.
