### ISSUE TITLE
Is BlazorWebAssemblyStandaloneWithIdentity safe to deploy to Azure App Service + Static Web App?

### ISSUE THREAD

**Issue by julioct** [dotnet/blazor-samples#159]
After going through [the BlazorWebAssemblyStandaloneWithIdentity example](https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAssemblyStandaloneWithIdentity), which works great, I want to make sure ASP.NET Core Identity with Cookie Authentication is still the right choice after deploying this to Azure. 

Specifically, I have deployed my apps, following the approach in this example, like this:

* Blazor WASM standalone app hosted in Azure Static Web App (https://brave-field-0f649a310.4.azurestaticapps.net)
* ASP.NET Core API hosted in Azure App Service (https://gamestore01.azurewebsites.net) 

The apps work mostly without issues in Azure, but I did have to add this to my API for cookies to work properly:

```csharp
builder.Services.ConfigureApplicationCookie(options =>
{
    options.Cookie.SameSite = SameSiteMode.None;
    options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
});
```

I want to make sure ASP.NET Core Identity is the recommended approach in this scenario, as opposed to using an OIDC server. I went through the guidance on [this official doc](https://learn.microsoft.com/aspnet/core/security/how-to-choose-identity-solution) and after following this diagram:

![image](https://github.com/dotnet/blazor-samples/assets/2374270/c730bb87-7a39-4ad1-a6b2-8d387dbd8cbf)

...it is not clear to me if my Blazor WASM standalone app, which lives in Azure Static Web App, should be classified as external or internal, which is the first decision point. I own both the API and the Blazor app, but it's not like they live in the same domain (given the different URLs provided by App Service and Static App).

Could you please clarify if the approach in the BlazorWebAssemblyStandaloneWithIdentity sample is recommended when deploying to Azure App Service + Azure Static Web App?

---
#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment]
Hello @julioct ... Could you open this over on the main repo from the **Open a documentation issue** link/feedback form at the bottom of the article? Just copy and paste your entire opening comment into the new issue's comment box.

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-identity?view=aspnetcore-8.0
