### ISSUE TITLE
Refactor WASM+Identity sample app to remove Swashbuckle?

### ISSUE THREAD

**Issue by guardrex** [dotnet/blazor-samples#168]
@JeremyLikness ... The `Backend` app of the WASM+Identity sample app uses Swashbuckle ...

```xml
<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
```

... but I thought it wasn't supported for 8.0 per ...

https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-7.0&tabs=visual-studio

**Comment by JeremyLikness** [comment]
Right. Agreed.
