### ISSUE TITLE
request a sample of PWA of Blazor WebApp using InteractiveClient 

### ISSUE THREAD

**Issue by odyyudah** [dotnet/blazor-samples#174]
**Describe the issue**
In .NET 7 we have a sample of Hosted Wasm PWA, but it is gone in .NET 8.
Request a sample of PWA of Blazor WebApp using InteractiveClient.

**Comment by guardrex** [comment]
Hello @odyyudah ... That's not a supported hosting scenario for a PWA. Currently, PWA is limited to the Blazor WebAssembly app template. You can open an issue for the product unit with your request at ...

https://github.com/dotnet/aspnetcore/issues
