### ISSUE TITLE
Request a sample BlazorWebApp WithIdentity

### ISSUE THREAD

**Issue by odyyudah** [dotnet/blazor-samples#201]
**Describe the issue**
Dear @guardrex , We are grateful to already have BlazorWebAssemblyStandaloneWithIdentity (Backend and BlazorWasmAuth)
Please kindly request a sample BlazorWebApp WithIdentity (Backend and BlazorWebAppAuth)
Thank you
---
#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment]
Hello ... This year, only the OIDC samples will be provided by the ASP.NET Core team ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=without-bff-pattern

More samples might be produced by the Azure documentation team, but I don't know when they plan to provide them.

**Comment by guardrex** [comment]
It isn't up to me. The product unit made the decision. Open an issue on their repo for your request, but note that they've told me that these are the only samples that they will be providing this year. The Azure documentation team said that they will be adding one or more samples, but I don't know exactly what type(s) of samples they will add, and I don't know when they will add them. 

Also note that such an app isn't called a "WebAPP" ... they won't even necessarily be able to understand what you're asking for. I think what you're asking for is a "Blazor Web App with only Server interactivity and OIDC."

Open an issue for them here ...

https://github.com/dotnet/aspnetcore/issues
