### ISSUE TITLE
There is no registered service of type 'BlazorWebAppOidc.Client.Weather.IWeatherForecaster'

### ISSUE THREAD

**Issue by tle5** [dotnet/blazor-samples#211]
**Describe the issue**
Open url: https://localhost:5001/weather

**To Reproduce**
1. Go to project BlazorWebAppOidc
2. Press F5 to debug
3. Open link: https://localhost:5001/weather

**Expected behavior**
An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot provide a value for property 'WeatherForecaster' on type 'BlazorWebAppOidc.Client.Pages.Weather'. There is no registered service of type 'BlazorWebAppOidc.Client.Weather.IWeatherForecaster'.
Microsoft.AspNetCore.Components.ComponentFactory+<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)

**Screenshots**
![image](https://github.com/dotnet/blazor-samples/assets/3350456/d14aa487-0c14-473a-91dc-adb6912eab1f)

**Additional context**
Add any other context about the issue here.

**.NET Version**
Output of `dotnet --info`.

---
#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment]
Hello @tle5 ... Yes, I see what you mean. If the user is returned from the IdP directly to the page, the page is rendered server side without a service registration. If some other page is rendered first, the app switches over to CSR (client-side rendering). Under CSR, the `Weather` component is rendered where the service is registered. I'm going to see if merely registering the service on the server will do the trick. *Stand-by ................*

**Comment by guardrex** [comment]
What I'll need to do is create a shared project for a shared `IWeatherForecaster` ... and the client will use the existing `ClientWeatherForecaster` implemention ... the server project will get a new `ServerWeatherForecaster` implementation. That's really the correct general approach. It's more work than I can do on a Sunday morning here in a few minutes, so I'll work on this on Monday.
