### ISSUE TITLE
Continuous Integration build for basic verification?

### ISSUE THREAD

**Issue by hakenr** [dotnet/blazor-samples#236]
Would you mind if I added a simple GitHub workflow to check the buildability of the solutions with every change pushed to this repo?

**Comment by guardrex** [comment]
Sure ... I just activated the actions for the repo.

**Comment by guardrex** [comment]
If you get stuck without permissions, let me know. I think you're just adding the .NET CI bits for it (IIRC).

**Comment by guardrex** [comment]
I'll close this out.
