### ISSUE TITLE
8.0 - BlazorWebAppOidcBff - Missing Reference

### ISSUE THREAD

**Issue by cipherw0lf** [dotnet/blazor-samples#245]
**Describe the issue**

Build Error: The type or namespace name 'Projects' could not be found when running Aspire AppHost project in new sample OIDC-BFF app

**To Reproduce**

1. Clone 8.0/BlazorWebAppOidcBff project
2. Open Solution in VS 2022 (Latest Stable - Version 17.9.3)
3. Click debug on the Aspire.AppHost project

**Expected behavior**

App should run

**Actual Behaviour**

Build Error:
Error | CS0246 | The type or namespace name 'Projects' could not be found (are you missing a using directive or an assembly reference?) | Aspire.AppHost | 

**Additional context**

Uncertain how to reference the projects in the Aspire AppHost.

---
#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment]
Hello @cipherw0lf ... That's strange. These apps run here. I'll take a closer look, but I'm OOF for the day. I think the soonest I'll be able to investigate will be Saturday morning. I'll get back to you as soon as I can.

**Comment by guardrex** [comment]
BTW tho ...

> Click debug on the Aspire.AppHost project

I'm not aware that one would debug that project independently. Did you try debugging by starting the app from the server project normally (the BlazorWebAppOidcBff project) ... and then see if you can debug the Aspire.AppHost project starting that way?

**Comment by guardrex** [comment]
OK .... I'm *BACK*.

Yes, I think the problem here is that the project has to be started from the server project of the app. Let me see if an update to the README file(s) (two of them, this app and the BFF version of this app) will fix this problem.

**Comment by guardrex** [comment]
That's interesting ... the guidance came over to start the app that way ...

> Select the `Aspire/Aspire.AppHost` project in Solution Explorer and start the app with either Visual Studio's Run button or by selecting Start Debugging from the Debug menu.

**Comment by guardrex** [comment]
I just noticed that the versions of the packages aren't updated (at least in one of the projects). That will need to be fixed. I'll put a PR up now to address it. This particular sample is one that I never ran locally due to the additional configuration required for Aspire (IIRC :thinking:).
