### ISSUE TITLE
Missing Button Type attribute

### ISSUE THREAD

**Issue by Phil-mcc** [dotnet/blazor-samples#264]
In 8.0/BlazorWebAppEFCore/Components/ContactForm.razor the cancel button lacks a type button.

```
<button disabled="@Busy" class="btn btn-warning"
           @onclick="CancelAsync">
           Cancel
</button>
```

Surely as default type in a form is submit this will call both submit and the CancelAsync?

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment]
Great catch, @Phil-mcc! ... This sample came over from the product unit; and although I did test it, I didn't pay close enough attention to spot it or test is closely enough. I'll fix it now.
