### ISSUE TITLE
Detailed tutorial on BlazorWebAppEFCore

### ISSUE THREAD

**Issue by adamcsillag** [dotnet/blazor-samples#287]
[This](https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?view=aspnetcore-8.0) tutorial is all I could find about [BlazorWebAppEFCore](https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAppEFCore). Is there a step-by-step guide on how to create it?

**Comment by guardrex** [comment]
Hello @adamcsillag ... Note for future reference to please open issues here using the **Open documentation issue** feedback link at the bottom of the article, which adds metadata and pings the author of a topic.

There is no step-by-step guide (tutorial) to create this app, but we'll be adding a new article in a a few weeks that will be a step-by-step tutorial to build a movie database, similar to the Razor Pages and MVC tutorials, per [Add a Blazor tutorial on using scaffolding to connect to data](https://github.com/dotnet/AspNetCore.Docs/issues/32359).
