### ISSUE TITLE
Blazor WASM + Dotnet API example

### ISSUE THREAD

**Issue by jepperaskdk** [dotnet/blazor-samples#31]
I wish there was an example on setting up a Blazor ahead-of-time compiled WASM project, with a .NET API.
With Angular, we get the `spa.UseAngularCliServer(npmScript: "start");` - what is there for Blazor?

**Comment by guardrex** [comment]
Hello @jepperaskdk ... We're limited in the number of samples that we can support with the staffing level that we have available. AOT WASM is really just a few small steps away from a non-AOT WASM app. The guidance is here ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#ahead-of-time-aot-compilation
