### ISSUE TITLE
Bad Request - Request Too Long - IIS Server

### ISSUE THREAD

**Issue by kuldeepcis-lab** [dotnet/blazor-samples#344]
**Describe the issue**

I cloned the repository and started working with the [BlazorWebappOidc](https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAppOidc) project. I configured the Entra ID settings, such as the client ID and tenant ID, using the details from my Entra ID tenant account. After running the application locally on the Kestrel server with the HTTPS profile, the Blazor application launched successfully. The interface loaded in the browser, and I was able to log in using my Entra ID account. After a successful callback to my Blazor application URL, I was redirected and received the expected details (Such as Username, email address, etc).

However, when I deployed the same application on an IIS server, I encountered an issue. While the Blazor application opened, when I attempted to log in to my Microsoft Entra ID account, I received a **Bad Request - Request Too Long** (_HTTP Error 400. The size of the request headers is too long_) error after the callback.
 

A clear and concise description of what the issue is about.

**To Reproduce**

1. Go to repository and clone [BlazorWebappOidc](https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAppOidc) and Open the application in Visual Studio.
2. Provide the needed configuration like Tenant ID, Client ID, etc for your Microsoft Azure Entra ID.
3. Add an IIS Settings to launchsettings.json to run the application on IIS  locally then Run 
` "iisSettings": {
   "windowsAuthentication": false,
   "anonymousAuthentication": true,
   "iisExpress": {
     "applicationUrl": "http://localhost:46294",
     "sslPort": 44381
   }
 },"profiles": {
  "IIS Express": {
    "commandName": "IISExpress",
    "launchBrowser": true,
    "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
    "environmentVariables": {
      "ASPNETCORE_ENVIRONMENT": "Development"
    }
  }
}`
4. Click on login and it will redirect you to the authentication flow then provide the Credentials for login (Entra ID Username and password).
5. After the successful callback you get back to the Blazor Application and then you will see the Error 
**Bad Request - Request Too Long** (_HTTP Error 400. The size of the request headers is too long._)

**Expected behavior**

After a successful callback to my Blazor application URL, I was redirected and received the expected details (Such as Username, email address, etc).

**Screenshots**

![Screenshot_11](https://github.com/user-attachments/assets/f776f0be-53c8-446f-9d52-79a9ce1c54b3)

![Screenshot_9](https://github.com/user-attachments/assets/78000d65-fdae-4f80-a7eb-62eb1b92e8e4)

![Screenshot_10](https://github.com/user-attachments/assets/56481a95-3e99-48ac-98c5-d37169705953)

**Additional context**

This is so strange to me why I am getting this issue, I have used the same app registration to do the authentication for the Blazor web assembly application (7.0) and it is working on the IIS Server there is no problem, I am getting the expected details from Entra ID.
But in the [BlazorWebappOidc](https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAppOidc) this is not working.

Any advice would be appreciated.

---
#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment]
Perhaps, it might be due to IIS Express, which doesn't use exactly the same configuration or work exactly the same way that IIS does.

Open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

You should be able to copy-paste most of your remarks directly into the new issue.

Please add ...

```
cc: @guardrex https://github.com/dotnet/blazor-samples/issues/344
```

... to the bottom of your opening comment so that I can follow the discussion.
