### ISSUE TITLE
.NET MAUI Blazor Hybrid and Web App with Entra

### ISSUE THREAD

**Issue by Megasoft2** [dotnet/blazor-samples#363]
Hi
Any sample code related to
.NET MAUI Blazor Hybrid and Web App with Entra

Thanks.

**Comment by guardrex** [comment]
Not here, but try the MAUI samples and articles elsewhere. For example, I see ...

* https://learn.microsoft.com/en-us/entra/external-id/customers/how-to-mobile-app-maui-sample-sign-in
* https://learn.microsoft.com/en-us/entra/external-id/customers/tutorial-mobile-app-maui-sign-in-prepare-tenant
* https://github.com/Azure-Samples/ms-identity-dotnetcore-maui

... based on a quick search.
