### ISSUE TITLE
Calling /confirmEmail endpoint ends in 401

### ISSUE THREAD

**Issue by lolhans** [dotnet/blazor-samples#377]
**Describe the issue**

I played around with the NET8.0/BlazorWebAssemblyStandaloneWithIdentity sample. Somehow i didn't found a way to confirm an email address, because i always got an 401 response. But that does not really make sense to me, because i need to confirm my mail before beeing able to authorize. 

**To Reproduce**

1. Added an additional endpoint to get the ConfirmationLink in the wasm frontend for faster iterations
```
app.MapPost("/getEmailConfirmationLink", async (UserManager<AppUser> userManager, [FromBody] string email) =>
{
    var user = await userManager.FindByEmailAsync(email);
    if (user == null)
    {
        return Results.NotFound("User not found.");
    }

    var token = await userManager.GenerateEmailConfirmationTokenAsync(user);
    var frontendUrl = builder.Configuration["FrontendUrl"] ?? "https://localhost:7211";
    var confirmationLink = $"{frontendUrl}/confirmEmail?userId={user.Id}&code={Uri.EscapeDataString(token)}";

    //var result = await userManager.ConfirmEmailAsync(user, token); This works

    return Results.Ok(confirmationLink);
});
```

2. After registering I called this endpoint and got the link. When i click on the link or try to make an get request to the /confirmEmail endpoint, I always end up with the 401, beeing not authorized. Also i was not able to call the endpoint using swagger, because i get the same result there. The userId and token are correct, because `await userManager.ConfirmEmailAsync(user, token);` works.

3. I tried to debug the ConfirmEmail endpoint by scaffolding the identity endpoint. But as soon as i scaffold any identity endpoint, the project breaks and ends up not being buildable anymore. 

**Expected behavior**

Calling the /confirmEmail endpoint with a 200 response from the WASM. 

#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment]
Hello @lolhans ... This scenario is tracked by an issue on the docs repo, which is the repo that we use to track most of the work that we do ...

https://github.com/dotnet/AspNetCore.Docs/issues/33771

Note for future reference that it's best to open a new issue for the docs team using the **Open a documentation issue** link/feedback form at the bottom of the article. Use of the form adds metadata to your GitHub issue that cross-links the topic and pings the author automatically for a faster response. We usually only use the issues here on the sample repo for small sample problems.

For this particular scenario ... because I haven't had a chance to look at it ... you'll need to re-open this issue for the product unit on their repo. Open an issue for them here ...

https://github.com/dotnet/aspnetcore/issues

They usually need a minimal repro app placed into GitHub that demonstrates the issue. They usually pull your sample down and work with it to investigate the problem.

Please add the following to your opening comment, which includes a link to my documentation issue and my GH username ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/33771
```

I'll follow the discussion that you have with them and add notes to my docs issue for when I reach it.

**Comment by lolhans** [comment]
Thank you for the response. I figured out the problem through debugging the blazor server example with identity. the cause was that i did not use the right encoding...

it should have had additional encoding:
```
app.MapPost("/getEmailConfirmationLink", async (UserManager<AppUser> userManager, [FromBody] string email) =>
{
    var user = await userManager.FindByEmailAsync(email);
    if (user == null)
    {
        return Results.NotFound("User not found.");
    }

    var token = await userManager.GenerateEmailConfirmationTokenAsync(user);
    token = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(token));
    var frontendUrl = builder.Configuration["BackendUrl"] ?? "https://localhost:7211";
    var confirmationLink = $"{frontendUrl}/confirmEmail?userId={user.Id}&code={token}";

    // var result = await userManager.ConfirmEmailAsync(user, token);

    return Results.Ok(confirmationLink);
});
```

**Comment by guardrex** [comment]
Very well ... and this is cross-linked now to my issue, so I'll be sure to review it when I reach the issue for work.

**Comment by guardrex** [comment]
BTW @lolhans ...

I just got into the weeds this morning with the (***presumably*** 😄) built-in email confirmation system of `MapIdentityApi`.

I see that what you decided to do was roll your own confirmation email system, but that shouldn't ... again, ***in theory*** 😄 ... be required.

My understanding of what the product unit provided is that if email confirmation is required ... in other words, the backend has ...

```csharp
builder.Services.Configure<IdentityOptions>(
    IdentityConstants.ApplicationScheme,
    options =>
    {
        options.SignIn.RequireConfirmedEmail = true;
    });
```

... which specifies the correct authentication scheme of `IdentityConstants.ApplicationScheme`, and the app has a good `EmailSender` implementation of `IEmailSender` in place and registered ...

```csharp
builder.Services.AddTransient<IEmailSender<AppUser>, EmailSender>();
```

... ***and*** of course one needs an email provider for the `EmailSender` ... I'm using MailChimp with Mandrill.net.

When a user attempts to register (i.e., hits the `/register` endpoint in the backend with a username and password), Identity should ✨ ***automagically*** ✨ take care of sending them a confirmation email that includes a `/confirmEmail` link for the built-in `/confirmEmail` endpoint that confirms the account. Then, the user should be able to sign into the app. Until then, `/login` should fail.

Now, having said all of that and implemented it in a test app here, it just no-op'ed on me! ☹ When I sought to register a user, the backend just went ahead and registered the user. Login was then successful.

Next, I'll check my email provider is working through the backend first. If so, I'll study the `/register` API of `MapIdentityApi` in reference source to see why its just registering an account that isn't confirmed. Ultimately if I can't figure out what's going on, I'll hit up the product unit ... Stephen Halter/Mike Kistler ... to ask them what I'm doing wrong. Eventually, there will be a new article on the repo to explain how to implement account confirmation and PW recovery with this solution.

Anyway ... did you try this built-in approach/strategy first and found that it wasn't working for you? Or, did you need to roll your own account confirmation bits for some other reason and didn't try the built-in API yourself?

**Comment by guardrex** [comment]
# Rubber 🦆

Ok ... I spoke a little too soon. I can see in the MailChimp API log that the registration processing behind `/register` did indeed try to send the email ...

![Image](https://github.com/user-attachments/assets/2da68d08-63b1-4786-b22d-8831ee4e4f06)

Therefore, `options.SignIn.RequireConfirmedEmail` partially worked. It tried to send the message, but it went ahead and registered the account for login without the account having been confirmed.

I'll dig a bit deeper.

Also, my messages are being rejected by MailChimp for some reason, so I'll need to troubleshoot that as well.

**Comment by guardrex** [comment]
# Rubber 🦆 

> recipient-domain-mismatch

Ah! I see ... DEMO mode ... I can only send to a valid sender domain without a paid account. Ok ... that's fine. I'll fix that first.

**Comment by guardrex** [comment]
# Rubber 🦆 

Now, I think I'm hitting what you HIT ...

When I took the confirm email link from the message that Identity sent (and changed the URL encoded `&` from `&amp;` to `&`), I can see in network tools ...

![Image](https://github.com/user-attachments/assets/3541d398-0c0b-4ef4-aac0-0f1cf611db76)

# 💥

**Comment by lolhans** [comment]
I'm sorry to tell you, that this somehow overwhelms me a bit. The main thing that surprised me, that `var token = await userManager.GenerateEmailConfirmationTokenAsync(user);` api does not give me an url safe token out of the box. I haven't checked yet, if the build-in implementation of the IEmailSender is using this non encoded token as well. For me it was just more straight forward to display the link directly within the browser.

I did not have the issue, that I can login before clicking on the registration link as I remember. But I can try that out again in my side. 

But thank you for investigating this issue. And what I understoud now is that you are facing the same 401 issue I had too.

**Comment by guardrex** [comment]
It's actually quite a bit easier than rolling your own bits. I know it doesn't ***seem that way*** 🙈 based on what MS and others publish. My goal for this will be to produce a simple 1-2-3 step-by-step article for it to ✨ ***Just Work!***&trade; ✨.

>  I understoud now is that you are facing the same 401 issue I had too.

No, that's all good now. I fixed that problem. The token produced by Identity is correctly encoded, and it does work. That part worked well after I stripped off my stupid quote at the end of the link 🙈. It was just a stupid cut-'n-paste error from when I was moving the link from the email message to the browser's address bar to test it. That quote was throwing a bad format exception when the code was unencoded by the framework. If you have the right link ... URL encoded and no foul characters ... it should work. You should get the "Thank you for confirming your email." message, and I did. All good. 👍 

Anyway ... the problem still remains here that a user can sign into their account ***before*** using the `/confirmEmail` link, and that's a problem for sure. I'm asking them if I'm missing a configuration setting, but AFAIK ...

```csharp
builder.Services.Configure<IdentityOptions>(
    IdentityConstants.ApplicationScheme,
    options =>
    {
        options.SignIn.RequireConfirmedEmail = true;
    });
```

... that should've worked.

**Comment by guardrex** [comment]
I just figured it out. I was lifting weights 🏋‍♂💪😬 and mulling it over ... and then recalled that there's another config point .......

```csharp
builder.Services.AddIdentityCore<AppUser>(o => o.SignIn.RequireConfirmedEmail = true)
    .AddRoles<IdentityRole>()
    .AddEntityFrameworkStores<AppDbContext>()
    .AddApiEndpoints();
```

***That's IT!*** 🎉🍻 

... and then the message to users must be updated in the `Register` component (`Components/Identity/Register.razor`) ...

```diff
- <div class="alert alert-success">You successfully registered. Now you can <a href="login">login</a>.</div>
+ <div class="alert alert-success">You successfully registered. You must now confirm your account by clicking the link in the email that was sent to you. After confirming your account, you can <a href="login">login</a> to the app.</div>
```

... something like that.

Ok ... I have everything I need to get the draft PR up tomorrow. I'll ping u on the PR so you can see the whole process.

**Comment by guardrex** [comment]
Even better, add the resend link to it ...

> You successfully registered. You must now confirm your account by clicking the link in the email that was sent to you. After confirming your account, you can \<a href="login">login\</a> to the app. \<a href="resendConfirmationEmail">Resend email\</a>
