### ISSUE TITLE
Concurrency Field - Not Reacting to Parameters Changing

### ISSUE THREAD

**Issue by crazyfox55** [dotnet/blazor-samples#378]
https://github.com/dotnet/blazor-samples/blob/d000234099558a1db2258a77d242e04ef2a9cfe7/8.0/BlazorWebAppEFCore/Components/ConcurrencyField.razor#L36-L47

This should be using the `OnParametersSet`, such that when the `DbModel` changes the `property` is checked again. Also none of the properties of the `Contact` have `ConcurrencyCheck` attributes, so the newest EF core will not automatically fail. I suggest adding the `ConcurrencyCheck` attribute to at least one property or every property because the UI implies the whole object is checked for concurrency.

**Comment by guardrex** [comment]
Thanks for the report, @crazyfox55.

I'm moving this over to our actual working repo. We ask devs to open issues for us using the **Open a documentation issue** link/feedback form at the bottom of an article. Issues here are usually just for patch changes, and this one will need the product unit to get involved. Use of the automatic form from the bottom of an article adds metadata to the GitHub issue that cross-links the topic and pings the author automatically for a faster response.
