### ISSUE TITLE
Change hardcoded CSS link to assembly name in _Host.cshtml

### ISSUE THREAD

**Issue by iiKuzmychov** [dotnet/blazor-samples#63]
When someone wants to rename a project, linked CSS still has the old name, so it will not work.

**To Reproduce**
1. Rename (any selected) project using Visual Studio
2. Open Pages/_Host.cshtml
3. See old CSS link
4. (optional) Launch the website and see that the main CSS isn`t work

**Expected behavior**
CSS link will change on project renaming.

**Screenshots**
![image](https://user-images.githubusercontent.com/37931581/204364643-cdb2ecf3-369f-4796-9982-38c8388e6a3a.png)

**Proposed solution**
I propose changing a hardcoded project name to:
`<link href="@(typeof(App).Assembly.GetName().Name).styles.css" rel="stylesheet" />`
![image](https://user-images.githubusercontent.com/37931581/204365125-19fb6b1b-aabc-4af1-89b6-a5c480aac2fc.png)

**.NET Version**
Any.

---
#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment]
Hello @iiKuzmychov ... We won't be able to take this type of change on because these are linked into documents and use a stable set of by-design namespace names that match the app. Devs are supposed to just download, run, and take code bits out of these samples, not really base their own apps directly on these particular apps.

**Comment by iiKuzmychov** [comment]
Yes, but person who will copy _Host.cshtml file and change CSS link to mach him own project, also may want to rename his own project in future, so, on my opinion, it's good to show example how to do it properly without problems, aren't it?
