### ISSUE TITLE
FileUpload4.razor is missing according to documentation page

### ISSUE THREAD

**Issue by mortenmoulder** [dotnet/blazor-samples#94]
**Describe the issue**
The page `Pages/FileUpload4.razor` is missing. It's decribed [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-7.0&pivots=webassembly#upload-image-preview). It should show a complete example of how to preview images, preferably multiple.

I can find FileUpload3.razor (which is the wrong version) in these three locations:

```
‎5.0/BlazorSample_Server/Pages/file-uploads/FileUpload3.razor
‎6.0/BlazorSample_Server/Pages/file-uploads/FileUpload3.razor
‎7.0/BlazorSample_Server/Pages/file-uploads/FileUpload3.razor
```

---
#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment]
Hello @mortenmoulder ...

* Not every doc example is in the snippet samples of these apps by-design. When new content appears, code examples are usually placed in the article at the outset. Later, code examples move to the snippet sample apps. Sometimes, code moves back into the articles to simplify maintenance. In this case, I expect the code to move over here. However, it can't happen at this time. I'm too busy with .NET 8 updates. Moving code is broadly tracked by a work entry on https://github.com/dotnet/AspNetCore.Docs/issues/28001.
* I'm not sure what you mean by the remark, "which is the wrong version." Can you clarify what you mean?

**Comment by mortenmoulder** [comment]
Hello @guardrex. What I mean about "wrong version" is the FileUpload3. There's a 1, 2, and 3, but not a 4th version.

**Comment by guardrex** [comment]
That's correct. I usually create the snippet sample apps for the next release after RC1 is released (mid-September). There's usually too much churn in the framework prior to RC1 to create them.

Keep in mind that these snippet samples aren't really "sample apps" in the runnable sense. They supply code to the topics. That's their main purpose. It's covered in the README here and at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/?view=aspnetcore-7.0#sample-apps

**Comment by mortenmoulder** [comment]
Right, makes sense. I'm simply pointing out the page that's referenced is missing. I found a solution, though 😄
